import test from 'node:test';
import assert from 'node:assert/strict';
import {blocksFor,phaseOrder} from '../dist/program.js';
import {freshState,start,validateSet,skipRest,changeLevel,assertState,rotationPattern,phaseUnlockProgress,unlockPhase,modeUnlockProgress,unlockMode,powerExplosiveAvailable,recentPain,blockProgress} from '../dist/engine.js';
function completeActive(s,now=1000,rating='Correct'){while(s.active){if(s.active.stage==='rest')skipRest(s);s.active.draft.rating=rating;validateSet(s,now+=1000);}return now;}
function completeBlock(s,index,now=1000,rating='Correct'){const id=blocksFor(s)[index].id;if(blockProgress(s,id).done){s.cycle++;s.phaseCycle++;s.registry=null;}s.next=index;start(s,now);return completeActive(s,now,rating);}
function fakePassage(id,lineId,variantId,target,sets=2){return{id:`fake-${id}-${Math.random()}`,status:'complete',results:Array.from({length:sets},(_,i)=>({id,lineId,variantId,mode:'force',actual:target,target,rating:'Correct',series:i+1}))};}

test('la Phase 1 conserve A→E et ses exercices initiaux',()=>{const s=freshState(1);assert.deepEqual(blocksFor(s).map(b=>b.id),['A','B','C','D','E']);assert.deepEqual(blocksFor(s).map(b=>b.ids),[['pullup','hang'],['split','calf'],['pushup','dip'],['row','leg'],['bridge','tibialis']]);assert.equal(s.progress.verticalPull.force,0);assert.equal(s.levels.leg,1);assertState(s);});
test('un changement de palier en séance garde le passé et recompose les séries pas encore commencées',()=>{const s=freshState(1);start(s,10);validateSet(s,20);const done=structuredClone(s.active.results[0]);assert.equal(changeLevel(s,'pullup',1,30,'force'),true);assert.deepEqual(s.active.results[0],done);assert.equal(s.active.results[0].total,3);const remaining=s.active.plan.slice(s.active.cursor).filter(x=>x.id==='pullup');assert.deepEqual(remaining.map(x=>x.series),[2,3,4]);assert.ok(remaining.every(x=>x.level===1&&x.total===4));assertState(s);});
test('une baisse peut supprimer les séries excédentaires sans toucher aux séries faites',()=>{const s=freshState(1);s.progress.verticalPull.force=1;start(s,10);for(let i=0;i<3;i++){validateSet(s,20+i);if(s.active?.stage==='rest')skipRest(s);}const results=structuredClone(s.active.results);assert.equal(changeLevel(s,'pullup',-1,40,'force'),true);assert.deepEqual(s.active.results,results);assert.equal(s.active.plan[s.active.cursor].id,'hang');assertState(s);});
test('les progressions Force, Endurance et Puissance sont indépendantes',()=>{const s=freshState(1);s.modeUnlocks.horizontalPush.endurance=true;s.modeUnlocks.horizontalPush.power=true;changeLevel(s,'pushup',1,10,'force');changeLevel(s,'pushup',1,11,'endurance');assert.deepEqual(s.progress.horizontalPush,{force:1,endurance:1,power:0});assert.deepEqual(rotationPattern(s.modeUnlocks.horizontalPush),['force','force','endurance','force','power']);assert.deepEqual(rotationPattern({force:true,endurance:true,power:false}),['force','force','endurance','force','force']);});
test('les critères de phase sont des suggestions et le déblocage reste manuel',()=>{const s=freshState(0);s.phaseCycle=5;for(let cycle=3;cycle<=4;cycle++)for(const blockId of ['A','B','C','D','E'])s.history.push({id:`${cycle}-${blockId}`,blockId,phaseId:'phase1',phaseCycle:cycle,status:'complete',startedAt:cycle,finishedAt:cycle,pausedMs:0,plan:[],results:[{id:'pushup',lineId:'horizontalPush',mode:'force',level:0,variantId:'classique',variantName:'Pompes classiques',series:1,total:1,target:6,unit:'reps',actual:6,rating:'Correct',note:'',at:cycle}]});const p=phaseUnlockProgress(s,9*86400000);assert.equal(p.ready,true);assert.equal(s.phase.id,'phase1');assert.equal(unlockPhase(s,9*86400000),true);assert.equal(s.phase.id,'phase2a');assert.equal(s.next,0);assert.equal(s.phaseCycle,1);});
test('Endurance se débloque par ligne après le prérequis, jamais automatiquement',()=>{const s=freshState(1);s.progress.horizontalPush.force=2;s.registry=null;completeBlock(s,2,100);completeBlock(s,2,200);const p=modeUnlockProgress(s,'horizontalPush','endurance',300);assert.equal(p.ready,true);assert.equal(s.modeUnlocks.horizontalPush.endurance,false);assert.equal(unlockMode(s,'horizontalPush','endurance',300),true);assert.equal(s.modeUnlocks.horizontalPush.endurance,true);});
test('les prérequis Endurance respectent les variantes et les seuils de chaque ligne',()=>{const row=freshState(1);row.history.push(fakePassage('row','horizontalPull','actuel',8));assert.equal(modeUnlockProgress(row,'horizontalPull','endurance').ready,false);row.history.push(fakePassage('row','horizontalPull','actuel',12));assert.equal(modeUnlockProgress(row,'horizontalPull','endurance').ready,true);const posterior=freshState(1);posterior.history.push(fakePassage('bridge','posterior','une-jambe',10));assert.equal(modeUnlockProgress(posterior,'posterior','endurance').ready,false);posterior.history.push(fakePassage('hamstring','hamstring','court',6));assert.equal(modeUnlockProgress(posterior,'posterior','endurance').ready,true);});
test('la douleur bloque les suggestions et le déblocage Puissance',()=>{const s=freshState(1);s.phase={id:'complete',activatedAt:0};s.next=2;s.progress.horizontalPush.force=2;completeBlock(s,2,100,'Douleur / gêne');assert.equal(recentPain(s,'horizontalPush'),true);const p=modeUnlockProgress(s,'horizontalPush','power',20*86400000);assert.equal(p.ready,false);assert.equal(p.checks.find(c=>c.id==='pain').ok,false);});
test('trois passages préparatoires sont nécessaires avant le palier explosif',()=>{const s=freshState(1);s.phase={id:'complete',activatedAt:0};s.modeUnlocks.horizontalPush.endurance=true;s.modeUnlocks.horizontalPush.power=true;for(let i=0;i<3;i++){s.modeRotation.horizontalPush=4;completeBlock(s,2,100+i*100);}assert.equal(powerExplosiveAvailable(s,'horizontalPush'),true);assert.equal(changeLevel(s,'pushup',1,500,'power'),true);});
test('les alternances mollets et G1/G2 sont automatiques entre deux cycles',()=>{const s=freshState(1);s.phase={id:'phase2b',activatedAt:1};s.next=1;start(s,10);assert.ok(s.active.plan.filter(x=>x.id==='calf').every(x=>x.alternate==='genou-tendu'));completeActive(s,20);assert.equal(s.alternations.calfNext,'genou-flechi');s.phase={id:'phase2c',activatedAt:1};s.next=6;start(s,30);assert.equal(s.active.blockVariant,'G1');assert.deepEqual(s.active.exerciseOrder,['sidePlank','adductor']);completeActive(s,40);assert.equal(s.alternations.gNext,'G2');s.cycle++;s.phaseCycle++;s.registry=null;s.next=6;start(s,50);assert.deepEqual(s.active.exerciseOrder,['antiRotation','abductor']);});
test('toutes les phases ajoutent des fonctions sans retirer les précédentes',()=>{const s=freshState(1);let previous=new Set(blocksFor(s).flatMap(b=>b.ids));for(const id of phaseOrder.slice(1)){s.phase={id,activatedAt:1};const current=new Set(blocksFor(s).flatMap(b=>b.ids));for(const exercise of previous)assert.ok(current.has(exercise),`${exercise} doit rester en ${id}`);previous=current;}});
