import test from 'node:test';
import assert from 'node:assert/strict';
import {access,readFile} from 'node:fs/promises';
import {exercises,phases,blocksFor} from '../dist/program.js';
import {freshState} from '../dist/engine.js';

test('chaque variante possède un id stable, une fonction et des prescriptions finies',()=>{assert.ok(Object.keys(exercises).length>=20);for(const [id,e] of Object.entries(exercises))for(const [modeId,m] of Object.entries(e.modes)){assert.ok(m.steps.length,`${id}/${modeId}`);for(const step of m.steps){assert.ok(step.variantId&&step.variantName&&step.lineId);assert.ok(step.targets.length&&step.targets.every(Number.isFinite));assert.ok(step.rest>0&&step.instruction);assert.doesNotMatch(step.variantName,/à définir/i);}}});
test('la base complète contient A→G et les compléments santé',()=>{const s=freshState(1);s.phase={id:'complete',activatedAt:1};const blocks=blocksFor(s);assert.deepEqual(blocks.map(b=>b.id),['A','B','C','D','E','F','G']);const ids=blocks.flatMap(b=>b.ids);for(const id of ['scapPull','scapPush','hamstring','rearShoulder','pike','hollow','sidePlank','adductor'])assert.ok(ids.includes(id));assert.equal(phases.complete.label,'Base complète');});
test('les fiches restent entièrement textuelles',async()=>{const app=await readFile(new URL('../dist/app.js',import.meta.url),'utf8');for(const token of ['animation','media-steps','data-media-key','<img','animation-placeholder'])assert.equal(app.toLowerCase().includes(token),false,token);for(const token of ['<h3>Position</h3>','<h3>Exécution</h3>','À éviter','Arrêt :','levelControls(id,mode)'])assert.ok(app.includes(token),token);});
test('l’infrastructure d’animation a été supprimée du projet',async()=>{await assert.rejects(access(new URL('../dist/animation/',import.meta.url)));await assert.rejects(access(new URL('../scripts/build-animation-manifest.mjs',import.meta.url)));await assert.rejects(access(new URL('../ANIMATIONS.md',import.meta.url)));const pkg=await readFile(new URL('../package.json',import.meta.url),'utf8'),launcher=await readFile(new URL('../Demarrer.cmd',import.meta.url),'utf8');assert.equal(/animation/i.test(pkg+launcher),false);});
test('l’interface conserve les contrôles, profils, historique, import et techniques',async()=>{const app=await readFile(new URL('../dist/app.js',import.meta.url),'utf8'),sw=await readFile(new URL('../dist/sw.js',import.meta.url),'utf8');for(const token of ['data-delta="-1"','data-delta="1"','quick-level','levelControls','select-profile','create-test','copy-test','confirm-reset-test','history-view','history-period','history-exercise','confirm-reset-principal','confirm-import','unlock-phase','unlock-mode','technique.sessionCues'])assert.ok(app.includes(token),token);for(const asset of ['./storage.js','./stats.js','./technique.js'])assert.ok(sw.includes(asset),asset);assert.equal(sw.includes('./animation/'),false);});
