import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,start,validateSet,skipRest,currentSet,setExecutionMode,restSuggestion,beginSuggestedActivity,skipSuggestedActivity,blockProgress,cycleComplete,changeLevel,unlockPhase,unlockMode,phaseUnlockProgress,modeUnlockProgress} from '../dist/engine.js';
import {COMPATIBILITY,FILLERS,compatibility,estimateSetDuration,protectedRestSeconds,activityWindowSeconds,prospectiveCompatibility,scoreOfficialCandidate,selectOfficialCandidate,scoreFiller,selectFiller,fillerDose,scoreMobility,selectMobility,selectComplementary} from '../dist/scheduler.js';
import {overviewStats,exerciseStats} from '../dist/stats.js';
import {freshDatabase,migrateData} from '../dist/storage.js';
import {FLEXIBILITY_CATALOG} from '../dist/flexibility.js';

const enterRest=(mode='quality',now=1000)=>{const s=freshState(1);setExecutionMode(s,mode,2);start(s,10);validateSet(s,now);return s;};
const finishActive=s=>{let now=10000;while(s.active){if(s.active.stage==='rest')skipRest(s);else validateSet(s,++now);}return now;};
const mainOwner=s=>s.registry.units.find(x=>x.officialId===s.active.mainRest.ownerId);

test('chaque série officielle du cycle possède un identifiant unique et stable',()=>{const s=freshState(1),ids=s.registry.units.map(x=>x.officialId);assert.equal(ids.length,new Set(ids).size);assert.ok(ids.every(id=>id.includes('cycle1')&&id.includes('_set')));assert.deepEqual(s.registry.units.map(x=>x.status).every(x=>x==='pending'),true);});
test('le registre utilise pending, in_progress et completed',()=>{const s=freshState(1);start(s,10);const id=currentSet(s).officialId;assert.equal(s.registry.units.find(x=>x.officialId===id).status,'in_progress');validateSet(s,20);assert.equal(s.registry.units.find(x=>x.officialId===id).status,'completed');});
test('une série terminée ne réapparaît jamais après Express puis Qualité',()=>{const s=enterRest('express'),done=s.active.results[0].officialId;setExecutionMode(s,'quality',1100);skipRest(s);assert.notEqual(currentSet(s).officialId,done);assert.equal(s.registry.units.find(x=>x.officialId===done).status,'completed');});
test('un bloc partiellement complété expose son compte exact',()=>{const s=enterRest('quality'),p=blockProgress(s,'A');assert.equal(p.completed,1);assert.ok(p.total>1);assert.equal(p.partial,true);});
test('un bloc peut être entièrement complété par des séries Express',()=>{const s=enterRest('express'),units=s.registry.units.filter(x=>x.blockId==='B');for(const unit of units){s.active.suggestion={kind:'program',item:unit,assessment:{}};assert.equal(beginSuggestedActivity(s,2000),true);validateSet(s,3000);}assert.equal(blockProgress(s,'B').done,true);assert.ok(s.active.results.filter(r=>r.movedBy==='express').length===units.length);});
test('le cycle est terminé uniquement lorsque toutes les unités officielles le sont',()=>{const s=freshState(1);assert.equal(cycleComplete(s),false);for(const unit of s.registry.units.slice(0,-1))unit.status='completed';assert.equal(cycleComplete(s),false);s.registry.units.at(-1).status='completed';assert.equal(cycleComplete(s),true);});
test('le scheduler ne prélève jamais le cycle suivant',()=>{const s=enterRest('express'),owner=mainOwner(s),candidate=selectOfficialCandidate(s,owner,s.active.restUntil,1100);assert.ok(candidate);assert.equal(candidate.item.cycle,undefined);assert.equal(candidate.item.officialId.includes(`cycle${s.cycle}`),true);});

for(const [from,to] of [['quality','express'],['express','quality'],['express','density'],['hybrid','quality']])test(`changement ${from} → ${to} sans réinitialisation`,()=>{const s=enterRest(from),until=s.active.restUntil,id=s.active.mainRest.ownerId;assert.equal(setExecutionMode(s,to,1200),true);assert.equal(s.settings.executionMode,to);assert.equal(s.active.restUntil,until);assert.equal(s.active.mainRest.ownerId,id);});
test('un changement pendant le repos affecte la prochaine décision du scheduler',()=>{const s=enterRest('quality');assert.equal(restSuggestion(s,1100),null);setExecutionMode(s,'express',1200);assert.equal(restSuggestion(s,1200)?.kind,'program');});
test('un changement pendant une série laisse la série courante immuable',()=>{const s=freshState(1);start(s,10);const before=structuredClone(currentSet(s));setExecutionMode(s,'hybrid',20);changeLevel(s,'pullup',1,30,'force');assert.equal(currentSet(s).officialId,before.officialId);assert.equal(currentSet(s).variantId,before.variantId);assert.equal(currentSet(s).target,before.target);});

test('la matrice respecte toutes les entrées GREEN, ORANGE et RED',()=>{for(const [source,row] of Object.entries(COMPATIBILITY)){for(const family of row.green)assert.equal(compatibility(source,family),'GREEN');for(const family of row.orange)assert.equal(compatibility(source,family),'ORANGE');for(const family of row.red)assert.equal(compatibility(source,family),'RED');}});
test('le score Express normal accepte une association sûre',()=>{const s=enterRest('express'),owner=mainOwner(s),split=s.registry.units.find(x=>x.id==='split');const result=scoreOfficialCandidate(s,owner,split,s.active.restUntil,1100);assert.equal(result.level,'GREEN');assert.equal(result.eligible,true);assert.ok(result.score>=65);});
test('Prudent exige 80 tandis que Normal accepte 65',()=>{const s=enterRest('express'),owner=mainOwner(s),split=s.registry.units.find(x=>x.id==='split');s.settings.expressLevel='normal';assert.equal(scoreOfficialCandidate(s,owner,split,s.active.restUntil,1100).eligible,true);s.settings.expressLevel='prudent';assert.equal(scoreOfficialCandidate(s,owner,split,s.active.restUntil,1100).eligible,false);});
test('Maximal peut autoriser ORANGE au-dessus du seuil',()=>{const s=enterRest('express'),owner=mainOwner(s),pushup=s.registry.units.find(x=>x.id==='pushup');s.settings.expressLevel='maximal';const r=scoreOfficialCandidate(s,owner,pushup,s.active.restUntil,1100);assert.equal(r.level,'ORANGE');assert.equal(r.eligible,r.score>=55);});
test('les égalités sont résolues de manière déterministe',()=>{const s=enterRest('express'),owner=mainOwner(s),a=selectOfficialCandidate(s,owner,s.active.restUntil,1100),b=selectOfficialCandidate(s,owner,s.active.restUntil,1100);assert.equal(a.item.officialId,b.item.officialId);});
test('les zones protégées suivent Puissance, Force difficile, Force modérée et Endurance',()=>{assert.equal(protectedRestSeconds({mode:'power',rest:150,target:3,id:'pullup'}),150);assert.equal(protectedRestSeconds({mode:'force',rest:120,target:4,id:'pullup'}),60);assert.equal(protectedRestSeconds({mode:'force',rest:100,target:7,id:'pullup'}),45);assert.equal(protectedRestSeconds({mode:'endurance',rest:60,target:12,id:'pushup'}),20);});
test('la fenêtre garde dix secondes de marge avant la zone protégée',()=>{const item={mode:'force',rest:120,target:4,id:'pullup'};assert.equal(activityWindowSeconds(item,121000,1000),50);});
test('une candidate trop longue est refusée',()=>{const s=enterRest('express'),owner=mainOwner(s),split=s.registry.units.find(x=>x.id==='split');assert.ok(estimateSetDuration(split)>0);assert.equal(scoreOfficialCandidate(s,owner,split,12000,1100).eligible,false);});
test('une douleur récente exclut toute auto-sélection',()=>{const s=enterRest('express'),owner=mainOwner(s),split=s.registry.units.find(x=>x.id==='split');s.history.push({results:[{lineId:split.lineId,rating:'Douleur / gêne'}]});assert.equal(scoreOfficialCandidate(s,owner,split,s.active.restUntil,1100).eligible,false);});
test('deux passages Trop dur pénalisent fortement le score',()=>{const s=enterRest('express'),owner=mainOwner(s),split=s.registry.units.find(x=>x.id==='split');s.history.push({results:[{id:'split',rating:'Trop dur',actual:0,target:1},{id:'split',rating:'Trop dur',actual:0,target:1}]});const r=scoreOfficialCandidate(s,owner,split,s.active.restUntil,1100);assert.ok(r.score<65);});
test('Puissance interdit toute activité intermédiaire automatique',()=>{const s=enterRest('hybrid'),owner=mainOwner(s);owner.mode='power';assert.equal(restSuggestion(s,1100),null);});

test('plusieurs disponibilités temporelles restent indépendantes',()=>{const s=enterRest('express');s.registry.availability.pullup=121000;s.registry.availability.split=51000;assert.notEqual(s.registry.availability.pullup,s.registry.availability.split);setExecutionMode(s,'quality',2000);assert.equal(s.registry.availability.pullup,121000);assert.equal(s.registry.availability.split,51000);});
test('une activité insérée ne remet pas le chrono principal à zéro',()=>{const s=enterRest('express'),until=s.active.restUntil;s.active.suggestion=restSuggestion(s,1100);beginSuggestedActivity(s,1200);validateSet(s,30000);assert.equal(s.active.restUntil,until);});
test('le calcul reste exact après un saut temporel simulant l’arrière-plan',()=>{const s=enterRest('quality'),owner=mainOwner(s);assert.equal(activityWindowSeconds(owner,s.active.restUntil,1100)>activityWindowSeconds(owner,s.active.restUntil,50000),true);});

test('les doses fillers correspondent à Légère, Normale et Soutenue',()=>{for(const [id,f] of Object.entries(FILLERS)){assert.equal(fillerDose(id,'light'),f.doses.light);assert.equal(fillerDose(id,'normal'),f.doses.normal);assert.equal(fillerDose(id,'sustained'),f.doses.sustained);}});
test('un filler ne complète jamais une série officielle ni un palier',()=>{const s=enterRest('density'),beforePending=s.registry.units.filter(x=>x.status==='pending').length,before=structuredClone(s.progress);const suggestion=selectFiller(s,mainOwner(s),s.active.restUntil,1100);assert.ok(suggestion);s.active.suggestion=suggestion;beginSuggestedActivity(s,1200);validateSet(s,5000);assert.equal(s.registry.units.filter(x=>x.status==='pending').length,beforePending);assert.deepEqual(s.progress,before);assert.equal(s.active.supplementary.length,1);});
test('un filler de même famille que les deux prochaines unités est exclu',()=>{const s=enterRest('density'),owner=mainOwner(s);for(const unit of s.registry.units)if(unit.status==='pending'&&['pullup','hang'].includes(unit.id))unit.status='completed';const result=scoreFiller(s,owner,'squat',s.active.restUntil,1100);assert.equal(result.eligible,false);assert.match(result.reason,/officiel proche/);});
test('les limites fillers par famille sont respectées',()=>{const s=enterRest('density'),owner=mainOwner(s);s.settings.densityLevel='light';s.registry.fillers.push({family:'TI'});assert.equal(scoreFiller(s,owner,'tibialis',s.active.restUntil,1100).eligible,false);});
test('aucun filler n’est proposé pendant Puissance',()=>{const s=enterRest('density'),owner=mainOwner(s);owner.mode='power';assert.equal(selectFiller(s,owner,s.active.restUntil,1100),null);});
test('le réglage ON/OFF d’un filler est respecté',()=>{const s=enterRest('density'),owner=mainOwner(s);s.settings.fillerAllowed.tibialis=false;assert.equal(scoreFiller(s,owner,'tibialis',s.active.restUntil,1100).eligible,false);});

test('une série Express reste Programme et un filler reste Complémentaire',()=>{const s=enterRest('express'),unit=s.registry.units.find(x=>x.id==='split');s.active.suggestion={kind:'program',item:unit,assessment:{}};beginSuggestedActivity(s,1200);validateSet(s,2000);setExecutionMode(s,'density',2100);const filler=selectFiller(s,mainOwner(s),s.active.restUntil,2200);s.active.suggestion=filler;beginSuggestedActivity(s,2300);validateSet(s,3000);finishActive(s);const stats=overviewStats(s,'all',20000);assert.ok(stats.programSets>0);assert.equal(stats.complementarySets,1);assert.equal(stats.totalSets,stats.programSets+1);assert.equal(s.history.flatMap(h=>h.results).find(r=>r.officialId===unit.officialId).kind,'program');});
test('le détail d’exercice sépare Programme, Complémentaire et Total',()=>{const s=freshState(1);s.history=[{startedAt:1,finishedAt:2,status:'complete',results:[{id:'split',unit:'reps',actual:5,at:2,workMeta:{family:'JG'}}],supplementary:[{id:'filler:squat',unit:'reps',actual:8,at:2,family:'JG',kind:'supplementary'}]}];const stats=exerciseStats(s,'split','all',10);assert.equal(stats.programTotal,5);assert.equal(stats.complementaryTotal,8);assert.equal(stats.combinedTotal,13);});

test('un prérequis non atteint reste activable manuellement',()=>{const s=freshState(1),p=modeUnlockProgress(s,'horizontalPush','endurance');assert.equal(p.ready,false);assert.equal(unlockMode(s,'horizontalPush','endurance',2,true),true);assert.equal(s.modeUnlocks.horizontalPush.endurance,true);});
test('une phase anticipée peut être programmée au prochain cycle',()=>{const s=freshState(1),before=s.phase.id;assert.equal(phaseUnlockProgress(s,2).ready,false);assert.equal(unlockPhase(s,2,{force:true,apply:'next'}),true);assert.equal(s.phase.id,before);assert.equal(s.pendingPhase.id,'phase2a');});
test('une phase anticipée peut ajouter le travail du cycle actuel',()=>{const s=freshState(1),before=s.registry.units.length;assert.equal(unlockPhase(s,2,{force:true,apply:'current'}),true);assert.equal(s.phase.id,'phase2a');assert.ok(s.registry.units.length>before);});

test('les paramètres de sons persistent dans une sérialisation complète',()=>{const db=freshDatabase(1);db.profiles.principal.settings.sounds={enabled:false,rest:false,exercise:true,volume:'normal'};const restored=migrateData(JSON.parse(JSON.stringify(db)));assert.deepEqual(restored.profiles.principal.settings.sounds,db.profiles.principal.settings.sounds);});
test('sons désactivés est représenté explicitement sans modifier les chronos',()=>{const s=enterRest('quality'),until=s.active.restUntil;s.settings.sounds.enabled=false;assert.equal(s.active.restUntil,until);assert.equal(s.settings.sounds.enabled,false);});

test('Qualité impose aussi un repos entre deux exercices',()=>{const s=freshState(1);start(s,10);validateSet(s,20);skipRest(s);validateSet(s,30);skipRest(s);validateSet(s,40);assert.equal(s.active.stage,'rest');assert.equal(currentSet(s).id,'hang');assert.ok(s.active.restUntil>40);});
test('Express et Hybride traitent ce repos comme une fenêtre scheduler',()=>{for(const mode of ['express','hybrid']){const s=freshState(1);setExecutionMode(s,mode);start(s,10);validateSet(s,20);assert.ok(restSuggestion(s,21));}});
test('passer une suggestion ne marque aucun travail comme terminé',()=>{const s=enterRest('express'),suggestion=restSuggestion(s,1100),before=s.registry.units.filter(x=>x.status==='completed').length;assert.ok(suggestion);skipSuggestedActivity(s,false);assert.equal(s.registry.units.filter(x=>x.status==='completed').length,before);assert.equal(s.active.stage,'rest');});

test('la protection prospective vérifie la prochaine unité officielle',()=>{const s=enterRest('express');const assessment=prospectiveCompatibility(s,'JG');assert.equal(assessment.levels[0],'GREEN');assert.equal(assessment.eligible,true);});
test('une compatibilité RED avec la prochaine unité exclut automatiquement',()=>{const s=enterRest('express'),assessment=prospectiveCompatibility(s,'PH');assert.equal(assessment.levels[0],'RED');assert.equal(assessment.eligible,false);});
test('une compatibilité ORANGE avec la prochaine unité exige Maximal et coûte 25 points',()=>{const s=enterRest('express');const normal=prospectiveCompatibility(s,'AF',null,'normal'),maximal=prospectiveCompatibility(s,'AF',null,'maximal');assert.equal(normal.levels[0],'ORANGE');assert.equal(normal.eligible,false);assert.equal(maximal.eligible,true);assert.equal(maximal.penalty<=-25,true);});
test('la deuxième unité RED pénalise sans exclure',()=>{const s=enterRest('express'),future=s.registry.units.filter(x=>x.status==='pending').sort((a,b)=>a.order-b.order);future[0].workMeta.family='TV';future[1].workMeta.family='JG';const assessment=prospectiveCompatibility(s,'JG');assert.deepEqual(assessment.levels,['GREEN','RED']);assert.equal(assessment.eligible,true);assert.equal(assessment.penalty,-20);});
test('Tractions puis Pompes candidate avant Suspension est refusé en Normal',()=>{const s=enterRest('express');for(const unit of s.registry.units)if(unit.id==='pullup'&&unit.status==='pending')unit.status='completed';const owner=mainOwner(s),pushup=s.registry.units.find(x=>x.id==='pushup'&&x.status==='pending'),assessment=scoreOfficialCandidate(s,owner,pushup,s.active.restUntil,1100);assert.equal(s.registry.units.filter(x=>x.status==='pending').sort((a,b)=>a.order-b.order)[0].id,'hang');assert.equal(assessment.eligible,false);assert.match(assessment.reason,/officiel proche/);});

test('Densité Renforcement léger conserve le comportement des fillers',()=>{const s=enterRest('density');s.settings.densityActivityType='reinforcement';const suggestion=selectComplementary(s,mainOwner(s),s.active.restUntil,1100);assert.equal(suggestion.item.supplementaryType,'strength');});
test('Densité Mobilité ne choisit que le catalogue restMobility',()=>{const s=enterRest('density');s.settings.densityActivityType='mobility';const suggestion=selectComplementary(s,mainOwner(s),s.active.restUntil,1100);assert.equal(suggestion.item.supplementaryType,'mobility');assert.ok(suggestion.item.mobilityId);});
test('Densité Mixte choisit le meilleur score disponible',()=>{const s=enterRest('density');s.settings.densityActivityType='mixed';const owner=mainOwner(s),strength=selectFiller(s,owner,s.active.restUntil,1100),mobility=selectMobility(s,owner,s.active.restUntil,1100),chosen=selectComplementary(s,owner,s.active.restUntil,1100);assert.equal(chosen.assessment.score,Math.max(strength?.assessment.score??-Infinity,mobility?.assessment.score??-Infinity));});
test('Hybride utilise Mobilité après absence de série officielle compatible',()=>{const s=enterRest('hybrid');s.settings.densityActivityType='mobility';for(const id of Object.keys(s.settings.expressAllowed))s.settings.expressAllowed[id]=false;const suggestion=restSuggestion(s,1100);assert.equal(suggestion.item.supplementaryType,'mobility');});
test('la mobilité protège fortement la prochaine unité officielle',()=>{const s=enterRest('density'),owner=mainOwner(s),next=s.registry.units.filter(x=>x.status==='pending').sort((a,b)=>a.order-b.order)[0];next.workMeta.family='JG';const assessment=scoreMobility(s,owner,'n22',s.active.restUntil,1100);assert.equal(assessment.eligible,false);assert.match(assessment.reason,/prochaine unité/);});
test('une mobilité de repos est enregistrée comme Complémentaire Mobilité',()=>{const s=enterRest('density');s.settings.densityActivityType='mobility';s.active.suggestion=restSuggestion(s,1100);beginSuggestedActivity(s,1200);validateSet(s,5000);const result=s.active.supplementary[0];assert.equal(result.kind,'supplementary');assert.equal(result.supplementaryType,'mobility');assert.ok(result.mobilityId);assert.equal(s.registry.units.filter(x=>x.status==='completed').length,1);});
test('passer une mobilité ne crée aucun résultat',()=>{const s=enterRest('density');s.settings.densityActivityType='mobility';assert.ok(restSuggestion(s,1100));skipSuggestedActivity(s,false);assert.equal(s.active.supplementary.length,0);assert.equal(s.active.stage,'rest');});

test('les pools Mobilité standard et conditionnel sont exactement ceux demandés',()=>{assert.deepEqual(Object.values(FLEXIBILITY_CATALOG).filter(x=>x.restPool==='standard').map(x=>x.id),['n1','n2','n7','n10','n15','n16','n35']);assert.deepEqual(Object.values(FLEXIBILITY_CATALOG).filter(x=>x.restPool==='conditional').map(x=>x.id),['n3','n4','n9','n14','n22','n24','n33','n34']);assert.equal(Object.values(FLEXIBILITY_CATALOG).filter(x=>x.usableAsRestMobility).length,15);});
test('le même nXX est interdit parmi les quatre dernières offres complémentaires',()=>{const s=enterRest('density'),owner={mode:'force',rest:180,target:10,workMeta:{family:'MO'}};for(const unit of s.registry.units.filter(x=>x.status==='pending'))unit.workMeta.family='MO';s.registry.activityOffers=[{type:'strength',id:'squat'},{type:'mobility',id:'n1',zone:'Épaules / haut du dos'}];const result=scoreMobility(s,owner,'n1',200000,1100);assert.equal(result.eligible,false);assert.match(result.reason,/quatre derniers/);});
test('une zone principale récente est fortement pénalisée',()=>{const s=enterRest('density'),owner={mode:'force',rest:180,target:10,workMeta:{family:'MO'}};for(const unit of s.registry.units.filter(x=>x.status==='pending'))unit.workMeta.family='MO';const before=scoreMobility(s,owner,'n1',200000,1100);s.registry.activityOffers=[{type:'mobility',id:'n2',zone:FLEXIBILITY_CATALOG.n1.primaryZone}];const after=scoreMobility(s,owner,'n1',200000,1100);assert.equal(after.score,before.score-25);});
test('aucun candidat varié et compatible produit un repos passif',()=>{const s=enterRest('density'),owner=mainOwner(s);for(const id of Object.keys(s.settings.mobilityAllowed))s.settings.mobilityAllowed[id]=false;assert.equal(selectMobility(s,owner,s.active.restUntil,1100),null);});
