import test from 'node:test';
import assert from 'node:assert/strict';
import {exercises} from '../dist/program.js';
import {freshState,start,validateSet} from '../dist/engine.js';
import {freshDatabase,migrateData,parseImport,assertDatabase,createTestProfile,switchProfile,resetTest,resetPrincipal,restoreBackup,deleteBackup} from '../dist/storage.js';

const legacy=()=>({version:1,revision:7,createdAt:10,next:0,cycle:2,levels:{pullup:1,hang:1,split:1,calf:1,pushup:1,dip:1,row:1,leg:1,bridge:1,tibialis:1},levelChanges:[],active:null,history:[{id:'old-1',block:0,cycle:1,startedAt:20,finishedAt:30,status:'complete',pausedMs:0,plan:[{id:'pullup',level:1,series:1,total:3,target:1,unit:'reps'}],results:[{id:'pullup',level:1,series:1,total:3,target:1,unit:'reps',actual:1,rating:'Correct',note:'ancienne note',at:25,timedSeconds:null}]}]});

test('une sauvegarde V1 est migrée sans perdre historique, note ni progression',()=>{const db=migrateData(legacy(),100);assertDatabase(db);const p=db.profiles.principal;assert.equal(p.schemaVersion,7);assert.equal(p.history[0].results[0].note,'ancienne note');assert.equal(p.history[0].results[0].target,1);assert.equal(p.history[0].results[0].variantId,'stricte');assert.equal(p.progress.verticalPull.force,0);assert.equal(p.cycle,2);assert.ok(p.registry.units.length);});
test('un échec de migration ne modifie pas les données originales',()=>{const source={version:999,history:[{note:'à garder'}]},before=structuredClone(source);assert.throws(()=>migrateData(source),/Version/);assert.deepEqual(source,before);assert.throws(()=>parseImport('{cassé'),/JSON valide/);});
test('Principal et Test sont isolés, y compris après copie et reset Test',()=>{const db=freshDatabase(1);db.profiles.principal.progress.horizontalPush.force=3;db.profiles.principal.history.push({id:'principal-only'});createTestProfile(db,true,2);assert.equal(db.activeProfile,'test');db.profiles.test.progress.horizontalPush.force=8;db.profiles.test.history.push({id:'test-only'});assert.equal(db.profiles.principal.progress.horizontalPush.force,3);assert.equal(db.profiles.principal.history.length,1);resetTest(db,3);assert.equal(db.profiles.test.history.length,0);assert.equal(db.profiles.principal.history.length,1);switchProfile(db,'principal');assert.equal(db.activeProfile,'principal');});
test('le premier reset Principal crée un backup restaurable',()=>{const db=freshDatabase(1);db.profiles.principal.progress.horizontalPush.force=4;resetPrincipal(db,'auto',10);assert.equal(db.profiles.principal.progress.horizontalPush.force,0);assert.equal(db.resetBackup.profile.progress.horizontalPush.force,4);restoreBackup(db);assert.equal(db.profiles.principal.progress.horizontalPush.force,4);});
test('un backup préexistant peut être gardé, remplacé ou supprimé explicitement',()=>{const keep=freshDatabase(1);keep.profiles.principal.progress.horizontalPush.force=1;resetPrincipal(keep,'auto',2);keep.profiles.principal.progress.horizontalPush.force=3;resetPrincipal(keep,'keep',3);assert.equal(keep.resetBackup.profile.progress.horizontalPush.force,1);const replace=freshDatabase(1);replace.profiles.principal.progress.horizontalPush.force=1;resetPrincipal(replace,'auto',2);replace.profiles.principal.progress.horizontalPush.force=3;resetPrincipal(replace,'replace',3);assert.equal(replace.resetBackup.profile.progress.horizontalPush.force,3);resetPrincipal(replace,'delete',4);assert.equal(replace.resetBackup,null);});
test('import valide accepté, structure invalide refusée',()=>{const db=freshDatabase(1),parsed=parseImport(JSON.stringify(db));assertDatabase(parsed);const broken=structuredClone(db);broken.profiles.principal.progress.horizontalPush.force=999;assert.throws(()=>parseImport(JSON.stringify(broken)),/Palier/);});
test('la suppression du backup ne touche pas aux profils',()=>{const db=freshDatabase(1);resetPrincipal(db,'auto',2);const principal=structuredClone(db.profiles.principal);deleteBackup(db);assert.equal(db.resetBackup,null);assert.deepEqual(db.profiles.principal,principal);});
test('la base complète persiste après sérialisation et rechargement',()=>{const db=freshDatabase(1);createTestProfile(db,true,2);db.profiles.test.levels.calf=2;db.profiles.principal.levels.calf=1;resetPrincipal(db,'auto',3);const restored=migrateData(JSON.parse(JSON.stringify(db)));assertDatabase(restored);assert.equal(restored.activeProfile,'principal');assert.equal(restored.profiles.test.levels.calf,2);assert.ok(restored.resetBackup);});

test('une base V3 migre vers V7 sans perdre profils, historique, séance active ni backup',()=>{const current=freshDatabase(1);current.profiles.principal.progress.horizontalPush.force=1;current.profiles.principal.history.push({id:'keep',startedAt:2,finishedAt:3,status:'complete',pausedMs:0,results:[],supplementary:[]});createTestProfile(current,true,4);current.activeProfile='principal';start(current.profiles.principal,10);validateSet(current.profiles.principal,20);const downgrade=profile=>{const old=structuredClone(profile);old.schemaVersion=3;delete old.flexibility;delete old.settings.densityActivityType;delete old.settings.mobilityAllowed;return old;},old={schemaVersion:3,revision:9,activeProfile:'principal',profiles:{principal:downgrade(current.profiles.principal),test:downgrade(current.profiles.test)},resetBackup:{savedAt:5,profile:downgrade(current.profiles.principal)}};const migrated=migrateData(old,100);assertDatabase(migrated);assert.equal(migrated.schemaVersion,7);assert.equal(migrated.revision,9);assert.equal(migrated.profiles.principal.progress.horizontalPush.force,1);assert.equal(migrated.profiles.principal.history[0].id,'keep');assert.ok(migrated.profiles.principal.active);assert.ok(migrated.profiles.test);assert.ok(migrated.resetBackup);assert.deepEqual(migrated.profiles.principal.flexibility,{history:[],active:null});assert.equal(migrated.profiles.principal.settings.densityActivityType,'reinforcement');});

test('une base V4 garde toute la musculation et marque la Souplesse historique legacy sans faux mapping',()=>{const current=freshDatabase(1),profile=current.profiles.principal;profile.progress.horizontalPush.force=2;profile.history.push({id:'muscle-v4',startedAt:2,finishedAt:3,status:'complete',pausedMs:0,results:[],supplementary:[]});profile.flexibility.history=[{id:'flex-v4',routineName:'Ancienne routine',startedAt:4,finishedAt:8,status:'complete',plan:[],results:[{id:'flex_old_unknown',exerciseId:'flex_old_unknown',name:'Ancien étirement',actualSeconds:22,rating:'Correct',note:'préservée',at:7}]}];const v4=structuredClone(current);v4.schemaVersion=4;v4.profiles.principal.schemaVersion=4;const migrated=migrateData(v4,100),next=migrated.profiles.principal,muscle=next.history[0];assert.equal(next.schemaVersion,7);assert.equal(muscle.id,'muscle-v4');assert.equal(muscle.startedAt,2);assert.equal(muscle.finishedAt,3);assert.deepEqual(muscle.results,[]);assert.deepEqual(muscle.supplementary,[]);assert.equal(next.progress.horizontalPush.force,2);assert.equal(next.flexibility.history[0].legacy,true);assert.equal(next.flexibility.history[0].sourceContext,'flexibility-legacy');assert.equal(next.flexibility.history[0].results[0].legacyId,'flex_old_unknown');assert.equal(next.flexibility.history[0].results[0].note,'préservée');assert.notEqual(next.flexibility.history[0].results[0].exerciseId,'n1');});
