import test from 'node:test';
import assert from 'node:assert/strict';
import {access,readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {exercises} from '../dist/program.js';
import {VISUAL_ATTRIBUTIONS,VISUAL_CATALOG,VISUAL_SUMMARY,VARIANT_VISUAL_INDEX,playbackSequence,visualFor} from '../dist/visual-catalog.js';

const allVariantKeys=()=>new Set(Object.entries(exercises).flatMap(([exerciseId,exercise])=>Object.values(exercise.modes).flatMap(mode=>mode.steps.map(step=>`${exerciseId}:${step.variantId}`))));

test('le catalogue couvre les 159 variantes et les 86 mouvements visuels',()=>{assert.equal(Object.keys(VARIANT_VISUAL_INDEX).length,159);assert.equal(Object.keys(VISUAL_CATALOG).length,86);assert.equal(VISUAL_SUMMARY.variants,159);assert.equal(VISUAL_SUMMARY.visualMovements,86);assert.deepEqual(allVariantKeys(),new Set(Object.keys(VARIANT_VISUAL_INDEX)));});

test('aucun statut bloquant ni visuel distant ne subsiste',()=>{assert.equal(VISUAL_SUMMARY.missing,0);assert.equal(VISUAL_SUMMARY.humanReviewRequired,0);assert.equal(VISUAL_SUMMARY.dedicatedVisualRequired,0);for(const visual of Object.values(VISUAL_CATALOG)){assert.ok(['MATCH_EXACT','MATCH_ACCEPTABLE','USE_PARENT_VISUAL','TEXT_SUFFICIENT'].includes(visual.resolutionStatus));for(const frame of visual.frames){assert.match(frame,/^\.\/assets\/exercises\//);assert.doesNotMatch(frame,/^https?:/);}}});

test('chaque fichier visuel déclaré existe localement',async()=>{for(const visual of Object.values(VISUAL_CATALOG))for(const frame of visual.frames)await access(new URL(`../dist/${frame.slice(2)}`,import.meta.url));});

test('les 95 fichiers visuels utiles sont présents par source',async()=>{const count=async source=>(await readdir(new URL(`../dist/assets/exercises/${source}/`,import.meta.url),{recursive:true,withFileTypes:true})).filter(item=>item.isFile()&&/\.(?:svg|png|webp|jpe?g)$/i.test(item.name)).length;assert.deepEqual({workoutGuide:await count('workout-guide'),repdb:await count('repdb'),freeExerciseDb:await count('free-exercise-db'),custom:await count('custom')},{workoutGuide:73,repdb:14,freeExerciseDb:2,custom:6});assert.deepEqual(VISUAL_SUMMARY.assetFiles,{'workout-guide':73,repdb:14,'free-exercise-db':2,custom:6,total:95});});

test('les visuels parents se résolvent sans boucle et sans exposer un vide',()=>{for(const visual of Object.values(VISUAL_CATALOG).filter(item=>item.resolutionStatus==='USE_PARENT_VISUAL')){assert.ok(visual.parentVisualId);const [key]=visual.variantKeys,resolved=visualFor(...key.split(':'));assert.ok(resolved.frames.length>0,key);assert.notEqual(resolved.effectiveVisualId,visual.visualId,key);}});

test('TEXT_SUFFICIENT reste volontairement sans image ni placeholder cassé',async()=>{const textOnly=Object.values(VISUAL_CATALOG).filter(item=>item.resolutionStatus==='TEXT_SUFFICIENT');assert.equal(textOnly.length,3);assert.ok(textOnly.every(item=>item.frames.length===0));const app=await readFile(new URL('../dist/app.js',import.meta.url),'utf8');assert.match(app,/resolutionStatus==='TEXT_SUFFICIENT'/);assert.doesNotMatch(app,/animation-placeholder|image-placeholder/);});

test('les six images custom sont affectées aux cinq mouvements attendus',()=>{const tib=VISUAL_CATALOG['visual-tibialis-wall-raise'],single=VISUAL_CATALOG['visual-tibialis-single-leg'],copenhagen=VISUAL_CATALOG['visual-copenhagen-dynamic'],copenhagenShort=VISUAL_CATALOG['visual-copenhagen-short'],reverse=VISUAL_CATALOG['visual-reverse-crunch-long-lever'];assert.deepEqual(tib.frames,['./assets/exercises/custom/tibialis-wall-low.webp','./assets/exercises/custom/tibialis-wall-high.webp']);assert.deepEqual(single.frames,tib.frames);assert.deepEqual(copenhagen.frames,['./assets/exercises/custom/copenhagen-low.webp','./assets/exercises/custom/copenhagen-high.webp']);assert.deepEqual(copenhagenShort.frames,['./assets/exercises/custom/copenhagen-high.webp']);assert.deepEqual(reverse.frames,['./assets/exercises/custom/reverse-crunch-long-low.webp','./assets/exercises/custom/reverse-crunch-long-high.webp']);assert.deepEqual(visualFor('reverseCrunch','levier-allonge-pause').frames,visualFor('reverseCrunch','levier-allonge').frames);});

test('aucune capture tierce ou ressource watermarkée n’est livrée',async()=>{const files=await readdir(new URL('../dist/assets/exercises/',import.meta.url),{recursive:true,withFileTypes:true}),names=files.filter(item=>item.isFile()).map(item=>item.name.toLowerCase());assert.equal(names.some(name=>/screenshot|capture|watermark/.test(name)),false);});

test('chaque manifeste contient uniquement ses phases utiles, dans l’ordre avant',()=>{const complexExpected=new Set(['visual-pushup-archer','visual-hamstring-walkout','visual-hamstring-walkout-bilateral','visual-reverse-snow-angel','visual-bird-dog','visual-shoulder-taps']);for(const visual of Object.values(VISUAL_CATALOG)){assert.ok(visual.frames.length<=3,visual.visualId);assert.deepEqual(visual.sequence,visual.frames.map((_,index)=>index),visual.visualId);assert.equal(new Set(visual.frames).size,visual.frames.length,visual.visualId);if(!visual.frames.length)continue;if(visual.animationMode==='STATIC')assert.equal(visual.frames.length,1,visual.visualId);if(visual.animationMode==='DYNAMIC_SIMPLE')assert.equal(visual.frames.length,2,visual.visualId);if(visual.animationMode==='DYNAMIC_COMPLEX')assert.equal(visual.frames.length,3,visual.visualId);}assert.deepEqual(new Set(Object.values(VISUAL_CATALOG).filter(item=>item.frames.length===3).map(item=>item.visualId)),complexExpected);});

test('le lecteur construit le ping-pong sans dupliquer les chemins du manifeste',()=>{assert.deepEqual(playbackSequence({sequence:[0]}),[0]);assert.deepEqual(playbackSequence({sequence:[0,1]}),[0,1]);assert.deepEqual(playbackSequence({sequence:[0,1,2]}),[0,1,2,1]);});

test('aucune animation ne contient deux fichiers binaires identiques',async()=>{for(const visual of Object.values(VISUAL_CATALOG)){const hashes=[];for(const frame of visual.frames){const bytes=await readFile(new URL(`../dist/${frame.slice(2)}`,import.meta.url));hashes.push(createHash('sha256').update(bytes).digest('hex'));}assert.equal(new Set(hashes).size,hashes.length,visual.visualId);}});

test('tractions et split squats utilisent exactement les phases auditées',()=>{const pullup=['./assets/exercises/workout-guide/pull-up/frame-3.svg','./assets/exercises/workout-guide/pull-up/frame-1.svg'];assert.deepEqual(VISUAL_CATALOG['visual-pullup-pronated'].frames,pullup);assert.deepEqual(VISUAL_CATALOG['visual-pullup-chest-high'].frames,pullup);for(const frame of VISUAL_CATALOG['visual-pullup-pronated'].frames)assert.doesNotMatch(frame,/frame-2\.svg$/);const split=['./assets/exercises/repdb/split-squat-start.webp','./assets/exercises/repdb/split-squat-peak.webp'];assert.deepEqual(VISUAL_CATALOG['visual-split-squat'].frames,split);assert.deepEqual(VISUAL_CATALOG['visual-glute-split-squat'].frames,split);});

test('les maintiens planche et handstand montrent la position finale correcte',()=>{assert.deepEqual(VISUAL_CATALOG['visual-front-plank'].frames,['./assets/exercises/workout-guide/plank/frame-1.svg']);assert.deepEqual(VISUAL_CATALOG['visual-wall-handstand-hold'].frames,['./assets/exercises/workout-guide/wall-handstand-push-up/frame-3.svg']);});

test('les commandes, l’agrandissement et les crédits sont accessibles dans l’interface',async()=>{const app=await readFile(new URL('../dist/app.js',import.meta.url),'utf8'),css=await readFile(new URL('../dist/style.css',import.meta.url),'utf8');for(const token of ['open-exercise-visual','close-exercise-visual','toggle-exercise-visual','previous-exercise-frame','next-exercise-frame','visual-attribution'])assert.ok(app.includes(token),token);for(const token of ['.exercise-visual-card','.exercise-visual-viewer','.exercise-visual-controls','.visual-attributions'])assert.ok(css.includes(token),token);assert.equal(VISUAL_ATTRIBUTIONS.length,4);});

test('le service worker précache le manifeste puis tous ses assets locaux',async()=>{const sw=await readFile(new URL('../dist/sw.js',import.meta.url),'utf8');assert.match(sw,/fetch\('\.\/visual-catalog\.json'\)/);assert.match(sw,/visualAssets/);assert.match(sw,/cache\.addAll\(\[\.\.\.SHELL,\.\.\.visualAssets\]\)/);assert.match(sw,/cache\.put\(event\.request,response\.clone\(\)\)/);});
